# Generated by Django 5.0.2 on 2024-02-27 16:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 2, 27, 16, 31, 48, 724004))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 2, 27, 16, 31, 48, 724004))),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CityPlace',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 2, 27, 16, 31, 48, 724004))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 2, 27, 16, 31, 48, 724004))),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.city')),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
