# Generated by Django 4.2.10 on 2024-02-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0009_alter_city_id_alter_cityplace_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.UUIDField(default='33adf3c3-1fb3-41a8-a258-f5de7cae53cf', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cityplace',
            name='id',
            field=models.UUIDField(default='33adf3c3-1fb3-41a8-a258-f5de7cae53cf', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
