# Generated by Django 5.0.2 on 2024-02-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default='6f96c3b7-fef8-42da-874e-bfbcf97b1e9c', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
