# Generated by Django 5.0.2 on 2024-03-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_alter_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='id',
            field=models.UUIDField(default='a95dd4c5-0d72-428a-80e6-51305da1e5fc', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
