# Generated by Django 5.0.2 on 2024-02-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenities', '0008_alter_amenity_created_at_alter_amenity_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='id',
            field=models.UUIDField(default='6f96c3b7-fef8-42da-874e-bfbcf97b1e9c', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
