# Generated by Django 5.0.2 on 2024-03-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenities', '0009_alter_amenity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='id',
            field=models.UUIDField(default='7a3be203-43dc-4246-a64c-b9bfb45a2db5', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
