# Generated by Django 5.0.2 on 2024-02-27 16:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 2, 27, 16, 31, 48, 724004))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 2, 27, 16, 31, 48, 724004))),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('number_rooms', models.IntegerField(default=0)),
                ('number_bathrooms', models.IntegerField(default=0)),
                ('rent_price', models.IntegerField(default=0)),
                ('latitude', models.DecimalField(decimal_places=4, default=0.0, max_digits=8, null=True)),
                ('longitude', models.DecimalField(decimal_places=4, default=0.0, max_digits=8, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 2, 27, 16, 31, 48, 724004))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 2, 27, 16, 31, 48, 724004))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaceProperty',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 2, 27, 16, 31, 48, 724004))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 2, 27, 16, 31, 48, 724004))),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
