# Generated by Django 5.0.2 on 2024-02-27 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amenities', '0001_initial'),
        ('places', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='place_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place'),
        ),
        migrations.AddField(
            model_name='placeproperty',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
        migrations.AddField(
            model_name='propertyamenity',
            name='amenity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amenities.amenity'),
        ),
        migrations.AddField(
            model_name='propertyamenity',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(related_name='property_amenities', through='properties.PropertyAmenity', to='amenities.amenity'),
        ),
    ]
