# Generated by Django 5.0.2 on 2024-02-27 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_placeproperty_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeproperty',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 17, 23, 48, 407585)),
        ),
        migrations.AlterField(
            model_name='placeproperty',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 17, 23, 48, 407585)),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 17, 23, 48, 407585)),
        ),
        migrations.AlterField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 17, 23, 48, 407585)),
        ),
        migrations.AlterField(
            model_name='propertyamenity',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 17, 23, 48, 407585)),
        ),
        migrations.AlterField(
            model_name='propertyamenity',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 17, 23, 48, 407585)),
        ),
    ]
