# Generated by Django 4.2.10 on 2024-02-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_alter_placeproperty_id_alter_property_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeproperty',
            name='id',
            field=models.UUIDField(default='33adf3c3-1fb3-41a8-a258-f5de7cae53cf', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default='33adf3c3-1fb3-41a8-a258-f5de7cae53cf', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='propertyamenity',
            name='id',
            field=models.UUIDField(default='33adf3c3-1fb3-41a8-a258-f5de7cae53cf', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
