# Generated by Django 5.0.2 on 2024-03-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_alter_placeproperty_id_alter_property_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeproperty',
            name='id',
            field=models.UUIDField(default='a95dd4c5-0d72-428a-80e6-51305da1e5fc', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default='a95dd4c5-0d72-428a-80e6-51305da1e5fc', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='propertyamenity',
            name='id',
            field=models.UUIDField(default='a95dd4c5-0d72-428a-80e6-51305da1e5fc', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
