# Generated by Django 5.0.2 on 2024-03-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_alter_placeproperty_id_alter_property_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeproperty',
            name='id',
            field=models.UUIDField(default='b2349bcb-5bc4-4116-bfa1-7d0d39317537', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default='b2349bcb-5bc4-4116-bfa1-7d0d39317537', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='propertyamenity',
            name='id',
            field=models.UUIDField(default='b2349bcb-5bc4-4116-bfa1-7d0d39317537', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
