# Generated by Django 5.0.2 on 2024-03-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_alter_placeproperty_id_alter_property_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeproperty',
            name='id',
            field=models.UUIDField(default='bcb716d9-e0de-4915-b0d7-33fc77d4de37', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default='bcb716d9-e0de-4915-b0d7-33fc77d4de37', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='propertyamenity',
            name='id',
            field=models.UUIDField(default='bcb716d9-e0de-4915-b0d7-33fc77d4de37', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
