# Generated by Django 5.0.2 on 2024-03-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_alter_placeproperty_id_alter_property_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeproperty',
            name='id',
            field=models.UUIDField(default='a247c71d-4a17-4f85-845b-55486a8eeecc', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default='a247c71d-4a17-4f85-845b-55486a8eeecc', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='propertyamenity',
            name='id',
            field=models.UUIDField(default='a247c71d-4a17-4f85-845b-55486a8eeecc', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
